# Generated by Django 3.2.6 on 2021-10-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '클릭 로그',
                'verbose_name_plural': '클릭 로그',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('is_hide', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('is_bad', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '수익금',
                'verbose_name_plural': '수익금',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '랜딩',
                'verbose_name_plural': '랜딩',
            },
        ),
        migrations.CreateModel(
            name='HotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('finish_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '핫타임',
                'verbose_name_plural': '핫타임',
            },
        ),
        migrations.CreateModel(
            name='IpOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_minutes', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '아이피 중복 체크',
                'verbose_name_plural': '아이피 중복 체크',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '랜딩',
                'verbose_name_plural': '랜딩',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=13, unique=True)),
                ('account_pw', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('media', models.CharField(max_length=30)),
                ('business', models.BooleanField(default=False)),
                ('ad_type', models.CharField(max_length=10)),
                ('memo', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('level', models.SmallIntegerField()),
                ('hiding_rate', models.SmallIntegerField()),
                ('commission_pc', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '파트너',
                'verbose_name_plural': '파트너',
            },
        ),
        migrations.CreateModel(
            name='PartnerLoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '파트너 로그인 기록',
                'verbose_name_plural': '파트너 로그인 기록',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('profit_bank_info', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '수익금 신청',
                'verbose_name_plural': '수익금 신청',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '스크립트',
                'verbose_name_plural': '스크립트',
            },
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['type', 'name'], name='script_search_common'),
        ),
        migrations.AddField(
            model_name='profit',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_agent', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='profit',
            name='register_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_register', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partnerloginlogs',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='domain',
            field=models.ManyToManyField(to='partners.Domain'),
        ),
        migrations.AddField(
            model_name='partner',
            name='hot_time',
            field=models.ManyToManyField(to='partners.HotTime'),
        ),
        migrations.AddField(
            model_name='partner',
            name='landing',
            field=models.ManyToManyField(to='partners.Landing'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='landing',
            name='script',
            field=models.ManyToManyField(to='partners.Script'),
        ),
        migrations.AddField(
            model_name='ipoverlap',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
        migrations.AddIndex(
            model_name='hottime',
            index=models.Index(fields=['start_at', 'finish_at'], name='hot_time_search_common'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['name'], name='domain_search_target'),
        ),
        migrations.AddField(
            model_name='commission',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members'),
        ),
        migrations.AddField(
            model_name='commission',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.payment'),
        ),
        migrations.AddField(
            model_name='click',
            name='landing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.landing'),
        ),
        migrations.AddField(
            model_name='click',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partners.partner'),
        ),
        migrations.AddIndex(
            model_name='profit',
            index=models.Index(fields=['status'], name='profit_search_common'),
        ),
        migrations.AddIndex(
            model_name='partnerloginlogs',
            index=models.Index(fields=['ip_address', 'created_at'], name='login_log_search_common'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['name', 'phone_number'], name='partner_search_target'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['media', 'business', 'ad_type', 'status', 'level', 'created_at'], name='partner_search_common'),
        ),
        migrations.AddIndex(
            model_name='landing',
            index=models.Index(fields=['routing_name'], name='landing_search_target'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['type', 'is_hide', 'is_bad', 'price', 'created_at'], name='commission_search_common'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip_address'], name='click_search_target'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['created_at'], name='click_search_common'),
        ),
    ]
