# Generated by Django 3.2.6 on 2021-11-11 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account_id',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', message='Username must be Alphanumeric')]),
        ),
    ]
