# Generated by Django 3.2.6 on 2021-11-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211108_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
