# Generated by Django 3.2.6 on 2021-11-11 03:31

from django.db import migrations, models
import members.validators.custom_validator


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_account_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankinfo',
            options={'verbose_name': '은행 정보'},
        ),
        migrations.AlterField(
            model_name='member',
            name='account_id',
            field=models.CharField(max_length=13, unique=True, validators=[members.validators.custom_validator.validate_alpha_num]),
        ),
    ]
