# Generated by Django 3.2.6 on 2021-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_device',
            field=models.CharField(blank=True, default='pc', max_length=10),
        ),
    ]
