# Generated by Django 3.2.6 on 2021-11-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_join_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_domain',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_intro_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_referer',
            field=models.URLField(blank=True, default=''),
        ),
    ]
